version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo installing maven...
      - yum install -y maven
  build:
    commands:
      - maven -v
      - java -version
      - echo building the justiceleague-tracker
      - mvn install
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
